// Case 3's laptop mockup keeps the real photo as the persistent hero
// background (so the desk/bezel/notebook stay at native image quality)
// and overlays just the screen-shaped slice of a separately-produced
// video on top of it. That video is regenerated by
// scripts/regenerate-onboarding-composite.py (source: assets/onboarding-
// flow.mp4, which is itself already a laptop-mockup render — the script
// crops out just its inner UI content before perspective-warping that crop
// onto the quad below, matching the photographed screen's tilt/keystone;
// see that script's module docstring for why the crop step is required and
// what to re-measure if onboarding-flow.mp4 is ever swapped for a new
// take). The composite's full 2400x1260 frame is sized to cover the whole
// hero exactly like a normal full-bleed video, with everything outside the
// quad discarded (filled black — irrelevant, since only the clip-path'd
// quad is ever visible and the real photo shows through everywhere else).
// `quad` is measured against that composite's native frame (order [TL, BL,
// BR, TR], matching SCREEN_RECTS's convention in hero-video-overlay.js) —
// it must stay in sync with QUAD in the regeneration script above.
const SCREEN_VIDEO_ONBOARDING = {
  src: 'assets/onboarding-desktop-composite.mp4',
  imageWidth: 2400, imageHeight: 1260,
  // Nudged ~2% outward from the measured screen corners (centered on the
  // quad's own centroid) so the clip-path fully covers the photographed
  // screen with a hair of overlap onto the black bezel rather than risking
  // a sliver of the blank-white mockup photo peeking through at the edge —
  // an overlap onto dark bezel is imperceptible, a gap onto white isn't.
  quad: [[566, 226], [604, 844], [1618, 781], [1578, 206]]
};

const CASES = {
  1: {
    video: 'assets/configurator-desktop-composite.mp4',
    photo: 'assets/Gemini_Generated_Image_qtfftwqtfftwqtff.jpeg',
    tags: ['B2B SaaS', 'Climate Tech'],
    title: 'Configurator',
    desc: 'A tool that helps asset managers explore renovation scenarios, improve energy efficiency, and optimize investment costs.'
  },
  2: {
    video: 'assets/portfolio-desktop-composite.mp4',
    photo: 'assets/portfolio-laptop-mockup.png',
    tags: ['B2B SaaS', 'Climate Tech'],
    title: 'Portfolio Overview',
    desc: 'Shifting from individual property views to portfolio-level intelligence, giving asset managers a clearer view of performance and where to act first.'
  },
  3: {
    photo: 'assets/photo_5829314581652770763_y.jpg',
    screenVideo: SCREEN_VIDEO_ONBOARDING,
    tags: ['B2B SaaS', 'Climate Tech'],
    title: 'Onboarding',
    desc: 'Guiding users from signup to first value through a simplified, flexible property creation flow that supports a self-serve experience.'
  }
};

// Extra zoom applied (centered on the hero) to the background photo and, in
// positionScreen(), to the matching screen-rect overlay in lockstep, so the
// laptop reads bigger without the two layers drifting out of alignment. Only
// used for cases with a screen overlay, where the screen content is the thing
// that needs to be legible.
const LAPTOP_ZOOM = 1.1;

// Case switches dissolve rather than cut. Text fades out/in on its own
// short timer. The hero video uses two stacked <video> elements so the
// incoming clip can fade in while the outgoing one is still fading out —
// a true crossfade with no moment where both are hidden and the plain
// .hero__bg shows through underneath.
const TEXT_FADE_MS = 180;
const VIDEO_CROSSFADE_MS = 500;

let renderCaseToken = 0;
let frontVideoIsA = true;

function getHeroVideos() {
  const a = document.getElementById('hero-video-a');
  const b = document.getElementById('hero-video-b');
  return frontVideoIsA ? { front: a, back: b } : { front: b, back: a };
}

// hero-video-overlay.js controls whichever clip is on top; tell it when
// that changes so its play/pause/frame-step controls follow the swap.
function announceActiveVideo(videoEl) {
  document.dispatchEvent(new CustomEvent('hero:active-video-changed', { detail: { video: videoEl } }));
}

// `onReveal` fires at the exact moment the new clip actually becomes
// visible (immediately if it's already showing, otherwise once it's
// buffered enough to play) — renderCase() uses it to time hiding the photo
// layer so that swap never race with this one and leave a gap where
// neither is visible (see renderCase()'s own comment on the matching
// video<->photo race this mirrors).
// `poster` is a static fallback frame for the browsers/settings that block
// autoplay outright (e.g. Brave's Shields ship an "Autoplay" permission,
// separate from Chrome's, that defaults to blocked per-site) — `back.play()`
// below is already allowed to fail silently, but without a poster a
// blocked/paused video with no decoded frame renders solid black instead of
// just sitting static, which reads the same as "the video never loaded."
function crossfadeToVideo(src, onReveal, poster) {
  const { front, back } = getHeroVideos();
  if (front.getAttribute('src') === src) {
    if (onReveal) onReveal();
    return; // already showing this clip
  }

  const token = renderCaseToken;
  const reveal = () => {
    if (token !== renderCaseToken) return;
    back.play().catch(() => {});
    back.classList.add('is-visible');
    front.classList.remove('is-visible');
    frontVideoIsA = !frontVideoIsA;
    announceActiveVideo(back);
    if (onReveal) onReveal();
    window.setTimeout(() => {
      if (token === renderCaseToken) front.pause();
    }, VIDEO_CROSSFADE_MS);
  };

  if (poster) back.poster = poster;
  back.setAttribute('src', src);
  back.load();
  if (back.readyState >= 2) reveal();
  else back.addEventListener('loadeddata', reveal, { once: true });
}

function renderCase(id) {
  const data = CASES[id];
  if (!data) return;

  const token = ++renderCaseToken;
  const titleEl = document.getElementById('case-title');
  const descEl = document.getElementById('case-desc');
  const photoEl = document.getElementById('hero-photo');

  titleEl.classList.add('is-switching');
  descEl.classList.add('is-switching');

  window.setTimeout(() => {
    if (token !== renderCaseToken) return; // a newer case switch took over
    titleEl.textContent = data.title;
    descEl.textContent = data.desc;
    titleEl.classList.remove('is-switching');
    descEl.classList.remove('is-switching');
  }, TEXT_FADE_MS);

  photoEl.style.transform = data.zoom ? `scale(${data.zoom})` : ((data.screenshot || data.screenVideo) ? `scale(${LAPTOP_ZOOM})` : '');

  // Whichever layer (video or photo) is leaving never starts fading out
  // until the incoming one is actually ready to show — hiding it
  // immediately on click, independent of the new layer's own load time,
  // left a gap on any real network latency where neither was visible and
  // the near-black .hero__bg showed through full-screen behind them
  // (confirmed by throttling the network while switching into case 3: the
  // outgoing video finished its fade-out well before the incoming photo's
  // preload resolved). crossfadeToVideo() already avoided this for
  // video<->video switches by keeping `front` visible until `back` is
  // ready; the branches below now follow the same rule for the video<->
  // photo switches only case 3 (the one case with no `data.video`) can
  // trigger.
  if (data.video) {
    crossfadeToVideo(data.video, () => {
      if (token !== renderCaseToken) return;
      photoEl.classList.add('is-loading');
    }, data.photo);
  } else {
    const { front } = getHeroVideos();
    if (data.photo) {
      const preload = new Image();
      preload.onload = () => {
        if (token !== renderCaseToken) return;
        photoEl.src = data.photo;
        photoEl.classList.remove('is-loading');
        front.pause();
        front.classList.remove('is-visible');
      };
      preload.src = data.photo;
    } else {
      photoEl.classList.add('is-loading');
      front.pause();
      front.classList.remove('is-visible');
    }
  }

  layoutScreen(data.screenshot);
  layoutScreenVideo(data.screenVideo);
}

let activeScreenshot = null;

function layoutScreen(screenshot) {
  activeScreenshot = screenshot || null;
  const screenEl = document.getElementById('hero-screen');

  if (!activeScreenshot) {
    screenEl.classList.remove('is-visible');
    screenEl.removeAttribute('src');
    return;
  }

  screenEl.src = activeScreenshot.src;
  positionScreen();
  screenEl.classList.add('is-visible');
}

function positionScreen() {
  if (!activeScreenshot) return;
  const screenEl = document.getElementById('hero-screen');
  const hero = document.querySelector('.hero');
  const rect = LaptopMockup.computeScreenRect(hero, activeScreenshot, LAPTOP_ZOOM);

  screenEl.style.left = `${rect.left}px`;
  screenEl.style.top = `${rect.top}px`;
  screenEl.style.width = `${rect.width}px`;
  screenEl.style.height = `${rect.height}px`;
  screenEl.style.borderRadius = `${Math.max(3, rect.width * 0.015)}px`;
}

let activeScreenVideo = null;

function layoutScreenVideo(screenVideo) {
  activeScreenVideo = screenVideo || null;
  const videoEl = document.getElementById('hero-screen-video');

  if (!activeScreenVideo) {
    videoEl.classList.remove('is-visible');
    videoEl.pause();
    videoEl.removeAttribute('src');
    return;
  }

  positionScreenVideo();

  const token = renderCaseToken;
  const reveal = () => {
    if (token !== renderCaseToken) return;
    videoEl.play().catch(() => {});
    videoEl.classList.add('is-visible');
    // hero-video-overlay.js's hover/expand/pause controls target whichever
    // <video> is "active"; for cases with a screen-video overlay (case 3)
    // that's this element rather than the full-bleed hero-video-a/b pair.
    announceActiveVideo(videoEl);
  };

  if (videoEl.getAttribute('src') !== activeScreenVideo.src) {
    // A stale first frame from the previous clip would otherwise flash
    // inside the new clip's clip-path the instant is-visible turns on, so
    // this clip only reveals once it actually has data of its own — same
    // readiness gate as crossfadeToVideo() above.
    videoEl.classList.remove('is-visible');
    videoEl.setAttribute('src', activeScreenVideo.src);
    videoEl.load();
    if (videoEl.readyState >= 2) reveal();
    else videoEl.addEventListener('loadeddata', reveal, { once: true });
  } else {
    reveal();
  }
}

// The composite's full frame is sized/positioned exactly like a normal
// full-bleed case video (cover-fit against the whole hero, via a `screen`
// spanning the entire frame) so it lines up pixel-for-pixel with the real
// photo underneath — same aspect ratio, same cover-fit math, just 2x the
// pixel coordinates. clip-path then keeps only the screen's quad visible;
// everywhere else, the untouched photo shows through.
function positionScreenVideo() {
  if (!activeScreenVideo) return;
  const videoEl = document.getElementById('hero-screen-video');
  const hero = document.querySelector('.hero');
  const { imageWidth, imageHeight, quad } = activeScreenVideo;
  const frameConfig = { imageWidth, imageHeight, screen: { left: 0, top: 0, right: imageWidth, bottom: imageHeight }, quad };
  const rect = LaptopMockup.computeScreenRect(hero, frameConfig, LAPTOP_ZOOM);
  const clipPath = LaptopMockup.quadClipPath(frameConfig);

  videoEl.style.left = `${rect.left}px`;
  videoEl.style.top = `${rect.top}px`;
  videoEl.style.width = `${rect.width}px`;
  videoEl.style.height = `${rect.height}px`;
  videoEl.style.clipPath = clipPath;
}

function initScreenResize() {
  let raf = null;
  window.addEventListener('resize', () => {
    if (raf) return;
    raf = requestAnimationFrame(() => {
      raf = null;
      positionScreen();
      positionScreenVideo();
    });
  });
}

function initCaseNav() {
  const tabs = document.querySelectorAll('.case-tab');
  tabs.forEach(tab => {
    tab.addEventListener('click', () => {
      tabs.forEach(t => {
        t.classList.remove('is-active');
        t.setAttribute('aria-selected', 'false');
      });
      tab.classList.add('is-active');
      tab.setAttribute('aria-selected', 'true');
      renderCase(tab.dataset.case);
      document.dispatchEvent(new CustomEvent('onboarding:case-change', { detail: { id: tab.dataset.case } }));
    });
  });
}

function initAbout() {
  const aboutSection = document.getElementById('about');
  const aboutTab = document.getElementById('about-tab');

  function setView(view) {
    const isAbout = view === 'about';
    document.body.classList.toggle('about-open', isAbout);
    aboutSection.setAttribute('aria-hidden', String(!isAbout));
    const label = aboutTab.querySelector('.side-tab__text');
    if (label) label.textContent = isAbout ? 'Close' : 'About';
    aboutTab.setAttribute('aria-selected', String(isAbout));
  }

  aboutTab.addEventListener('click', (e) => {
    e.preventDefault();
    setView(document.body.classList.contains('about-open') ? 'work' : 'about');
  });

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && document.body.classList.contains('about-open')) {
      setView('work');
    }
  });
}

// #case-detail has one section per case (data-case="N"); only the one
// matching the active case tab is shown. Mirrors how #story's ScrollStory
// instances key off the same 'onboarding:case-change' event via activateOn.
function initCaseDetailToggle() {
  document.addEventListener('onboarding:case-change', (e) => {
    const id = String(e.detail && e.detail.id);
    document.querySelectorAll('.case-detail').forEach(section => {
      section.classList.toggle('is-active', section.dataset.case === id);
    });
    // The progress trail (scroll-story.js) sizes itself off the active
    // case-detail's geometry, which just changed, but it only recomputes on
    // scroll/resize — nudge it so it doesn't sit stale until the next tick.
    window.dispatchEvent(new Event('scroll'));
  });
}

// Case-detail footer "Next case study" link — reuses the same case-tab
// switching logic (hero content + active .case-detail) rather than
// duplicating it, then scrolls to the newly-active section.
function initFooterCaseLinks() {
  document.querySelectorAll('[data-goto-case]').forEach(link => {
    link.addEventListener('click', (e) => {
      e.preventDefault();
      const id = link.dataset.gotoCase;
      const tab = document.querySelector('.case-tab[data-case="' + id + '"]');
      if (tab) tab.click();
      const target = document.getElementById('case-detail-' + id);
      if (target) target.scrollIntoView({ behavior: 'smooth' });
    });
  });
}

initCaseNav();
initFooterCaseLinks();
initAbout();
initCaseDetailToggle();
initScreenResize();
