// Case 3's laptop mockup keeps the real photo as the persistent hero
// background (so the desk/bezel/notebook stay at native image quality)
// and overlays just the screen-shaped slice of a separately-produced
// video on top of it. That video is regenerated by
// scripts/regenerate-onboarding-composite.py (source: assets/onboarding-
// flow.mp4, which is itself already a laptop-mockup render — the script
// crops out just its inner UI content before perspective-warping that crop
// onto the quad below, matching the photographed screen's tilt/keystone;
// see that script's module docstring for why the crop step is required and
// what to re-measure if onboarding-flow.mp4 is ever swapped for a new
// take). The composite's full 2400x1260 frame is sized to cover the whole
// hero exactly like a normal full-bleed video, with everything outside the
// quad discarded (filled black — irrelevant, since only the clip-path'd
// quad is ever visible and the real photo shows through everywhere else).
// `quad` is measured against that composite's native frame (order [TL, BL,
// BR, TR], matching SCREEN_RECTS's convention in hero-video-overlay.js) —
// it must stay in sync with QUAD in the regeneration script above.
const SCREEN_VIDEO_ONBOARDING = {
  src: 'assets/onboarding-desktop-composite.mp4',
  imageWidth: 2400, imageHeight: 1260,
  // Nudged ~2% outward from the measured screen corners (centered on the
  // quad's own centroid) so the clip-path fully covers the photographed
  // screen with a hair of overlap onto the black bezel rather than risking
  // a sliver of the blank-white mockup photo peeking through at the edge —
  // an overlap onto dark bezel is imperceptible, a gap onto white isn't.
  quad: [[566, 226], [604, 844], [1618, 781], [1578, 206]]
};

const CASES = {
  1: {
    video: 'assets/configurator-desktop-composite.mp4',
    photo: 'assets/Gemini_Generated_Image_qtfftwqtfftwqtff.jpeg',
    tags: ['B2B SaaS', 'Climate Tech'],
    title: 'Configurator',
    desc: 'A tool that helps asset managers explore renovation scenarios, improve energy efficiency, and optimize investment costs.',
    // Below the 980px breakpoint (see heroFocal()), anchors the mobile
    // cover-fit crop and its matching .hero__screen/.hero__screen-video
    // overlay. Plain center for all three cases below — left as a
    // per-case field rather than hardcoded, in case a specific case's
    // mockup crops better off-center (e.g. its screen content sits
    // noticeably left/right of the source photo/video's horizontal
    // middle, the axis actually being cropped on mobile).
    mobileFocus: { fx: 0.5, fy: 0.5 }
  },
  2: {
    video: 'assets/portfolio-desktop-composite.mp4',
    photo: 'assets/portfolio-laptop-mockup.png',
    tags: ['B2B SaaS', 'Climate Tech'],
    title: 'Portfolio Overview',
    desc: 'Shifting from individual property views to portfolio-level intelligence, giving asset managers a clearer view of performance and where to act first.',
    mobileFocus: { fx: 0.5, fy: 0.5 }
  },
  3: {
    photo: 'assets/photo_5829314581652770763_y.jpg',
    screenVideo: SCREEN_VIDEO_ONBOARDING,
    tags: ['B2B SaaS', 'Climate Tech'],
    title: 'Onboarding',
    desc: 'Guiding users from signup to first value through a simplified, flexible property creation flow that supports a self-serve experience.',
    mobileFocus: { fx: 0.5, fy: 0.5 }
  }
};

// Extra zoom applied (centered on the hero) to the background photo and, in
// positionScreen(), to the matching screen-rect overlay in lockstep, so the
// laptop reads bigger without the two layers drifting out of alignment. Only
// used for cases with a screen overlay, where the screen content is the thing
// that needs to be legible.
const LAPTOP_ZOOM = 1.1;

function laptopZoom() {
  return LAPTOP_ZOOM;
}

// Below 980px, .hero__photo/.hero__video's contain-fit anchor is the
// active case's mobileFocus (see CASES above and the @media
// (max-width: 980px) block in css/styles.css). computeScreenRect() takes
// the same focal point so .hero__screen/.hero__screen-video stay aligned
// to wherever that anchoring leaves the image.
function heroFocal() {
  if (!window.matchMedia('(max-width: 980px)').matches) return { fx: 0.5, fy: 0.5 };
  const data = CASES[activeCaseId];
  return (data && data.mobileFocus) || { fx: 0.5, fy: 0.5 };
}

// Both mobile and desktop crop the hero photo/video to fill their box
// (object-fit: cover), so the same crop-in zoom applies on both.
function applyPhotoZoom(data) {
  const photoEl = document.getElementById('hero-photo');
  const zoom = data.zoom || ((data.screenshot || data.screenVideo) ? laptopZoom() : null);
  photoEl.style.transform = zoom ? `scale(${zoom})` : '';
}

// Case switches dissolve rather than cut. Text fades out/in on its own
// short timer. The hero video uses two stacked <video> elements so the
// incoming clip can fade in while the outgoing one is still fading out —
// a true crossfade with no moment where both are hidden and the plain
// .hero__bg shows through underneath.
const TEXT_FADE_MS = 180;
const VIDEO_CROSSFADE_MS = 500;

let renderCaseToken = 0;
let frontVideoIsA = true;
// Mirrors the .case-tab.is-active default set in index.html, so the hero's
// initial (pre-any-click) focus point below matches case 1 rather than
// falling back to the centered default. Kept in sync by renderCase().
let activeCaseId = (document.querySelector('.case-tab.is-active') || {}).dataset
  ? document.querySelector('.case-tab.is-active').dataset.case
  : '1';

// Anchors the mobile cover-fit crop (--hero-focus-x/-y, read by
// .hero__photo/.hero__video in css/styles.css) on the given case's
// mobileFocus, defaulting to centered. Applied eagerly below for the
// page's initial case (renderCase() isn't called until a tab switch) and
// again from renderCase() itself on every subsequent switch.
function applyHeroFocus(data) {
  const hero = document.querySelector('.hero');
  const focus = (data && data.mobileFocus) || { fx: 0.5, fy: 0.5 };
  hero.style.setProperty('--hero-focus-x', (focus.fx * 100) + '%');
  hero.style.setProperty('--hero-focus-y', (focus.fy * 100) + '%');
}

function getHeroVideos() {
  const a = document.getElementById('hero-video-a');
  const b = document.getElementById('hero-video-b');
  return frontVideoIsA ? { front: a, back: b } : { front: b, back: a };
}

// hero-video-overlay.js controls whichever clip is on top; tell it when
// that changes so its play/pause/frame-step controls follow the swap.
function announceActiveVideo(videoEl) {
  document.dispatchEvent(new CustomEvent('hero:active-video-changed', { detail: { video: videoEl } }));
}

// `onReveal` fires at the exact moment the new clip actually becomes
// visible (immediately if it's already showing, otherwise once it's
// buffered enough to play) — renderCase() uses it to time hiding the photo
// layer so that swap never race with this one and leave a gap where
// neither is visible (see renderCase()'s own comment on the matching
// video<->photo race this mirrors).
// `poster` is a static fallback frame for the browsers/settings that block
// autoplay outright (e.g. Brave's Shields ship an "Autoplay" permission,
// separate from Chrome's, that defaults to blocked per-site) — `back.play()`
// below is already allowed to fail silently, but without a poster a
// blocked/paused video with no decoded frame renders solid black instead of
// just sitting static, which reads the same as "the video never loaded."
function crossfadeToVideo(src, onReveal, poster) {
  const { front, back } = getHeroVideos();
  if (front.getAttribute('src') === src) {
    if (onReveal) onReveal();
    return; // already showing this clip
  }

  const token = renderCaseToken;
  const reveal = () => {
    if (token !== renderCaseToken) return;
    back.play().catch(() => {});
    back.classList.add('is-visible');
    front.classList.remove('is-visible');
    frontVideoIsA = !frontVideoIsA;
    announceActiveVideo(back);
    if (onReveal) onReveal();
    window.setTimeout(() => {
      if (token === renderCaseToken) front.pause();
    }, VIDEO_CROSSFADE_MS);
  };

  if (poster) back.poster = poster;
  back.setAttribute('src', src);
  back.load();
  if (back.readyState >= 2) reveal();
  else back.addEventListener('loadeddata', reveal, { once: true });
}

function renderCase(id) {
  const data = CASES[id];
  if (!data) return;

  activeCaseId = String(id);
  applyHeroFocus(data);

  const token = ++renderCaseToken;
  const titleEl = document.getElementById('case-title');
  const descEl = document.getElementById('case-desc');
  const ghostTitleEl = document.getElementById('hero-ghost-title');
  const photoEl = document.getElementById('hero-photo');

  titleEl.classList.add('is-switching');
  descEl.classList.add('is-switching');

  window.setTimeout(() => {
    if (token !== renderCaseToken) return; // a newer case switch took over
    titleEl.textContent = data.title;
    descEl.textContent = data.desc;
    ghostTitleEl.textContent = data.title;
    titleEl.classList.remove('is-switching');
    descEl.classList.remove('is-switching');
  }, TEXT_FADE_MS);

  applyPhotoZoom(data);

  // Whichever layer (video or photo) is leaving never starts fading out
  // until the incoming one is actually ready to show — hiding it
  // immediately on click, independent of the new layer's own load time,
  // left a gap on any real network latency where neither was visible and
  // the near-black .hero__bg showed through full-screen behind them
  // (confirmed by throttling the network while switching into case 3: the
  // outgoing video finished its fade-out well before the incoming photo's
  // preload resolved). crossfadeToVideo() already avoided this for
  // video<->video switches by keeping `front` visible until `back` is
  // ready; the branches below now follow the same rule for the video<->
  // photo switches only case 3 (the one case with no `data.video`) can
  // trigger.
  if (data.video) {
    crossfadeToVideo(data.video, () => {
      if (token !== renderCaseToken) return;
      photoEl.classList.add('is-loading');
    }, data.photo);
  } else {
    const { front } = getHeroVideos();
    if (data.photo) {
      const preload = new Image();
      preload.onload = () => {
        if (token !== renderCaseToken) return;
        photoEl.src = data.photo;
        photoEl.classList.remove('is-loading');
        front.pause();
        front.classList.remove('is-visible');
      };
      preload.src = data.photo;
    } else {
      photoEl.classList.add('is-loading');
      front.pause();
      front.classList.remove('is-visible');
    }
  }

  layoutScreen(data.screenshot);
  layoutScreenVideo(data.screenVideo);
}

let activeScreenshot = null;

function layoutScreen(screenshot) {
  activeScreenshot = screenshot || null;
  const screenEl = document.getElementById('hero-screen');

  if (!activeScreenshot) {
    screenEl.classList.remove('is-visible');
    screenEl.removeAttribute('src');
    return;
  }

  screenEl.src = activeScreenshot.src;
  positionScreen();
  screenEl.classList.add('is-visible');
}

// #hero-media wraps the photo/video/screen/screen-video layers together
// (see index.html). On desktop it's position:static, so its absolutely
// positioned children (.hero__screen etc.) skip past it and attach to
// .hero as before — unaffected. Below 980px it becomes position:relative
// (see the @media block), so those same children anchor to #hero-media's
// own box instead: the box .hero__photo/.hero__video actually fill there,
// which is padded in from .hero's full width and much shorter than
// .hero's total height (which also includes the case-card content below
// it). Measuring against #hero-media directly means no origin offset is
// needed — left/top land in the right coordinate space already.
function positionScreen() {
  if (!activeScreenshot) return;
  const screenEl = document.getElementById('hero-screen');
  const hero = document.querySelector('.hero');
  const mediaEl = document.getElementById('hero-media');
  const mobile = window.matchMedia('(max-width: 980px)').matches;
  const measureEl = mobile ? mediaEl : hero;
  const rect = LaptopMockup.computeScreenRect(measureEl, activeScreenshot, laptopZoom(), heroFocal());

  screenEl.style.left = `${rect.left}px`;
  screenEl.style.top = `${rect.top}px`;
  screenEl.style.width = `${rect.width}px`;
  screenEl.style.height = `${rect.height}px`;
  screenEl.style.borderRadius = `${Math.max(3, rect.width * 0.015)}px`;
}

let activeScreenVideo = null;

function layoutScreenVideo(screenVideo) {
  activeScreenVideo = screenVideo || null;
  const videoEl = document.getElementById('hero-screen-video');

  if (!activeScreenVideo) {
    videoEl.classList.remove('is-visible');
    videoEl.pause();
    videoEl.removeAttribute('src');
    return;
  }

  positionScreenVideo();

  const token = renderCaseToken;
  const reveal = () => {
    if (token !== renderCaseToken) return;
    videoEl.play().catch(() => {});
    videoEl.classList.add('is-visible');
    // hero-video-overlay.js's hover/expand/pause controls target whichever
    // <video> is "active"; for cases with a screen-video overlay (case 3)
    // that's this element rather than the full-bleed hero-video-a/b pair.
    announceActiveVideo(videoEl);
  };

  if (videoEl.getAttribute('src') !== activeScreenVideo.src) {
    // A stale first frame from the previous clip would otherwise flash
    // inside the new clip's clip-path the instant is-visible turns on, so
    // this clip only reveals once it actually has data of its own — same
    // readiness gate as crossfadeToVideo() above.
    videoEl.classList.remove('is-visible');
    videoEl.setAttribute('src', activeScreenVideo.src);
    videoEl.load();
    if (videoEl.readyState >= 2) reveal();
    else videoEl.addEventListener('loadeddata', reveal, { once: true });
  } else {
    reveal();
  }
}

// The composite's full frame is sized/positioned exactly like a normal
// full-bleed case video (cover-fit against the whole hero, via a `screen`
// spanning the entire frame) so it lines up pixel-for-pixel with the real
// photo underneath — same aspect ratio, same cover-fit math, just 2x the
// pixel coordinates. clip-path then keeps only the screen's quad visible;
// everywhere else, the untouched photo shows through.
function positionScreenVideo() {
  if (!activeScreenVideo) return;
  const videoEl = document.getElementById('hero-screen-video');
  const hero = document.querySelector('.hero');
  const photoEl = document.getElementById('hero-photo');
  const { imageWidth, imageHeight, quad } = activeScreenVideo;
  const frameConfig = { imageWidth, imageHeight, screen: { left: 0, top: 0, right: imageWidth, bottom: imageHeight }, quad };
  const mobile = window.matchMedia('(max-width: 980px)').matches;
  const measureEl = mobile ? photoEl : hero;
  const originLeft = mobile ? photoEl.offsetLeft : 0;
  const originTop = mobile ? photoEl.offsetTop : 0;
  const rect = LaptopMockup.computeScreenRect(measureEl, frameConfig, laptopZoom(), heroFocal());
  const clipPath = LaptopMockup.quadClipPath(frameConfig);

  videoEl.style.left = `${rect.left + originLeft}px`;
  videoEl.style.top = `${rect.top + originTop}px`;
  videoEl.style.width = `${rect.width}px`;
  videoEl.style.height = `${rect.height}px`;
  videoEl.style.clipPath = clipPath;
}

// Configurator (case 1) / Portfolio Overview (case 2) mobile hero: each
// config's `bg` mockup photo supplies its own monitor/laptop+desk scene with
// a blank screen; #hero-mobile-screen-window/-video overlay just the
// app-content portion of the SAME composite video used by hero-video-a/b
// (CASES[id].video for cases 1/2, SCREEN_VIDEO_ONBOARDING.src for case 3),
// cropped to its own screen area (`videoScreen` - keep in sync with
// SCREEN_RECTS[id].screen in hero-video-overlay.js) and resized/positioned
// to land inside the photo's screen area instead. Axis-aligned only (no
// quad/perspective warp): unlike desktop's frame-registered photo+video
// pairings, this mobile photo isn't shot from the same camera/scene as the
// source video, so this is a best-fit crop rather than a pixel-exact
// composite.
// How much of the mobile viewport's width the mockup's screen area should
// span - 1 would be edge-to-edge (no backdrop visible at the sides); less
// than 1 zooms out slightly, leaving the mockup's own backdrop as a margin
// on both sides. Tune this one number to adjust the crop for both cases.
const MOBILE_SCREEN_WIDTH_FRACTION = 0.82;

const MOBILE_HERO_OVERLAY = {
  1: {
    videoSrc: 'assets/configurator-desktop-composite.mp4',
    bgImage: 'assets/configurator_mobile.jpeg',
    // Photographed at a slight tilt (top-right/bottom-left corners aren't
    // level with their opposite corner), so no axis-aligned rect can sit
    // corner-to-corner without either a visible white sliver or a hair of
    // overlap onto the bezel. `screen` is the bounding box of the measured
    // quad (used to size/position the window rect, cover-fit style); `quad`
    // is the actual 4 corners ([TL, BL, BR, TR]), nudged ~2% outward from
    // the measured white/bezel boundary (same reasoning as
    // SCREEN_VIDEO_ONBOARDING's quad above: an overlap onto the dark bezel
    // is imperceptible, a gap onto white isn't), clip-path'd onto the
    // window in positionMobileScreenOverlay() so the video reaches every
    // corner instead of leaving a sliver at the bbox rectangle's edges.
    bg: {
      imageWidth: 768, imageHeight: 1376,
      screen: { left: 156, top: 603, right: 643, bottom: 901 },
      quad: [[156, 603], [161, 901], [643, 886], [635, 623]]
    },
    videoScreen: { imageWidth: 2764, imageHeight: 1504, screen: { left: 584, top: 138, right: 2292, bottom: 1164 } }
  },
  2: {
    videoSrc: 'assets/portfolio-desktop-composite.mp4',
    bgImage: 'assets/portofolio_mobile.jpeg',
    bg: { imageWidth: 768, imageHeight: 1376, screen: { left: 194, top: 572, right: 573, bottom: 824 } },
    videoScreen: { imageWidth: 3390, imageHeight: 1856, screen: { left: 936, top: 382, right: 2454, bottom: 1224 } }
  },
  3: {
    videoSrc: 'assets/onboarding-desktop-composite.mp4',
    bgImage: 'assets/onboarding_mobile.png',
    // Laptop screen photographed at a tilt (right edge sits higher than
    // left) - same corner-to-corner treatment as case 1's quad above:
    // `screen` is the measured quad's bounding box, `quad` the actual 4
    // corners nudged ~2% outward, clip-path'd onto the window so the video
    // reaches every corner instead of leaving a sliver at the bbox edges.
    bg: {
      imageWidth: 940, imageHeight: 1672,
      screen: { left: 178, top: 744, right: 616, bottom: 1019 },
      quad: [[178, 758], [196, 1019], [616, 990], [598, 744]]
    },
    videoScreen: { imageWidth: 2400, imageHeight: 1260, screen: { left: 576, top: 212, right: 1608, bottom: 838 } }
  }
};

function positionMobileScreenOverlay() {
  const windowEl = document.getElementById('hero-mobile-screen-window');
  const videoEl = document.getElementById('hero-mobile-screen-video');
  if (!windowEl || !videoEl) return;
  const config = MOBILE_HERO_OVERLAY[activeCaseId];
  if (!config || !window.matchMedia('(max-width: 980px)').matches) return;

  const sourceEl = videoEl.querySelector('source');
  if (sourceEl.getAttribute('src') !== config.videoSrc) {
    sourceEl.setAttribute('src', config.videoSrc);
    videoEl.load();
    videoEl.play().catch(() => {});
  }

  const mediaEl = document.getElementById('hero-media');
  const mediaW = mediaEl.offsetWidth;
  const mediaH = mediaEl.offsetHeight;
  if (!mediaW || !mediaH) return;

  // Zoomed in past plain cover-fit: scale is set so the photo's own screen
  // area spans MOBILE_SCREEN_WIDTH_FRACTION of the viewport width, centered
  // (leaving backdrop visible on both sides), rather than cover's smaller
  // (height-driven) scale or a full edge-to-edge fit.
  const bg = config.bg;
  const screenNativeW = bg.screen.right - bg.screen.left;
  const bgScale = (mediaW * MOBILE_SCREEN_WIDTH_FRACTION) / screenNativeW;
  const bgOffsetX = (mediaW - screenNativeW * bgScale) / 2 - bg.screen.left * bgScale;
  const renderedH = bg.imageHeight * bgScale;
  // Centering on the screen's own vertical midpoint can push the (now
  // smaller, zoomed-out) image far enough that one edge no longer reaches
  // mediaEl's bounds, leaving a gap where the page's own background shows
  // through - clamp back into the range that always fully covers mediaH.
  const desiredOffsetY = mediaH / 2 - ((bg.screen.top + bg.screen.bottom) / 2) * bgScale;
  const bgOffsetY = Math.min(0, Math.max(mediaH - renderedH, desiredOffsetY));

  mediaEl.style.backgroundImage = `url('${config.bgImage}')`;
  mediaEl.style.backgroundRepeat = 'no-repeat';
  mediaEl.style.backgroundSize = `${bg.imageWidth * bgScale}px ${bg.imageHeight * bgScale}px`;
  mediaEl.style.backgroundPosition = `${bgOffsetX}px ${bgOffsetY}px`;

  const winLeft = bgOffsetX + bg.screen.left * bgScale;
  const winTop = bgOffsetY + bg.screen.top * bgScale;
  const winWidth = (bg.screen.right - bg.screen.left) * bgScale;
  const winHeight = (bg.screen.bottom - bg.screen.top) * bgScale;

  windowEl.style.left = `${winLeft}px`;
  windowEl.style.top = `${winTop}px`;
  windowEl.style.width = `${winWidth}px`;
  windowEl.style.height = `${winHeight}px`;
  // Cuts the window's bbox rect down to the true (tilted) screen quad when
  // one is given, so the video reaches every corner with no white sliver
  // left showing past it. Percentage-based, so it's valid regardless of
  // winWidth/winHeight - see quadClipPath()'s own comment.
  windowEl.style.clipPath = bg.quad ? LaptopMockup.quadClipPath(bg) : '';

  // Same cover-fit math again, this time fitting just the video's own
  // screen-content crop (not its full baked scene) into that window.
  const vs = config.videoScreen;
  const screenW = vs.screen.right - vs.screen.left;
  const screenH = vs.screen.bottom - vs.screen.top;
  const vScale = Math.max(winWidth / screenW, winHeight / screenH);
  const cropExtraX = (winWidth - screenW * vScale) / 2;
  const cropExtraY = (winHeight - screenH * vScale) / 2;

  videoEl.style.width = `${vs.imageWidth * vScale}px`;
  videoEl.style.height = `${vs.imageHeight * vScale}px`;
  videoEl.style.left = `${-vs.screen.left * vScale + cropExtraX}px`;
  videoEl.style.top = `${-vs.screen.top * vScale + cropExtraY}px`;
}

function initScreenResize() {
  let raf = null;
  window.addEventListener('resize', () => {
    if (raf) return;
    raf = requestAnimationFrame(() => {
      raf = null;
      const data = CASES[activeCaseId];
      if (data) applyPhotoZoom(data);
      positionScreen();
      positionScreenVideo();
      positionMobileScreenOverlay();
    });
  });
  document.addEventListener('onboarding:case-change', positionMobileScreenOverlay);
  positionMobileScreenOverlay();
}

function initCaseNav() {
  const tabs = document.querySelectorAll('.case-tab');
  tabs.forEach(tab => {
    tab.addEventListener('click', () => {
      tabs.forEach(t => {
        t.classList.remove('is-active');
        t.setAttribute('aria-selected', 'false');
      });
      tab.classList.add('is-active');
      tab.setAttribute('aria-selected', 'true');
      renderCase(tab.dataset.case);
      document.dispatchEvent(new CustomEvent('onboarding:case-change', { detail: { id: tab.dataset.case } }));
    });
  });
}

function initAbout() {
  const aboutSection = document.getElementById('about');
  const aboutTab = document.getElementById('about-tab');

  let currentView = 'work';

  function setView(view) {
    currentView = view;
    const isAbout = view === 'about';
    document.body.classList.toggle('about-open', isAbout);
    aboutSection.setAttribute('aria-hidden', String(!isAbout));
    const label = aboutTab.querySelector('.side-tab__text');
    // On mobile the word is replaced by .side-tab__arrow's existing
    // underline-to-cross animation rather than a second, literal "x"
    // glyph — an aria-label stands in for the accessible name the
    // visible word used to provide. On desktop there's room for the
    // word itself, so it stays as "Close" instead of disappearing.
    const isMobile = window.matchMedia('(max-width: 980px)').matches;
    if (label) label.textContent = isAbout ? (isMobile ? '' : 'Close') : 'About';
    if (isAbout && isMobile) {
      aboutTab.setAttribute('aria-label', 'Close');
    } else {
      aboutTab.removeAttribute('aria-label');
    }
    aboutTab.setAttribute('aria-selected', String(isAbout));
  }

  aboutTab.addEventListener('click', (e) => {
    e.preventDefault();
    setView(document.body.classList.contains('about-open') ? 'work' : 'about');
  });

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && document.body.classList.contains('about-open')) {
      setView('work');
    }
  });

  // Keep the label's mobile/desktop wording in sync if the viewport
  // crosses the 980px breakpoint while the panel is already open.
  window.addEventListener('resize', () => setView(currentView));
}

// #case-detail has one section per case (data-case="N"); only the one
// matching the active case tab is shown. Mirrors how #story's ScrollStory
// instances key off the same 'onboarding:case-change' event via activateOn.
function initCaseDetailToggle() {
  document.addEventListener('onboarding:case-change', (e) => {
    const id = String(e.detail && e.detail.id);
    document.querySelectorAll('.case-detail').forEach(section => {
      section.classList.toggle('is-active', section.dataset.case === id);
    });
    // The progress trail (scroll-story.js) sizes itself off the active
    // case-detail's geometry, which just changed, but it only recomputes on
    // scroll/resize — nudge it so it doesn't sit stale until the next tick.
    window.dispatchEvent(new Event('scroll'));
  });
}

// Case-detail footer "Next case study" link — reuses the same case-tab
// switching logic (hero content + active .case-detail) rather than
// duplicating it, then scrolls to the newly-active section.
function initFooterCaseLinks() {
  document.querySelectorAll('[data-goto-case]').forEach(link => {
    link.addEventListener('click', (e) => {
      e.preventDefault();
      const id = link.dataset.gotoCase;
      const tab = document.querySelector('.case-tab[data-case="' + id + '"]');
      if (tab) tab.click();
      const target = document.getElementById('case-detail-' + id);
      if (target) target.scrollIntoView({ behavior: 'smooth' });
    });
  });
}

initCaseNav();
initFooterCaseLinks();
initAbout();
initCaseDetailToggle();
initScreenResize();
